[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context."staging/convoltaje-superadmin".environment]
  VITE_SUPABASE_URL = "https://fvcjxujqeruzzxejtmcs.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_FHLFogIGgGEyM0X7_zcqQA_7GXON-6n"

[context.branch-deploy.environment]
  VITE_SUPABASE_URL = "https://fvcjxujqeruzzxejtmcs.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_FHLFogIGgGEyM0X7_zcqQA_7GXON-6n"

[context.deploy-preview.environment]
  VITE_SUPABASE_URL = "https://fvcjxujqeruzzxejtmcs.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_FHLFogIGgGEyM0X7_zcqQA_7GXON-6n"
